// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mongodb/mongodb-cli/mongocli/v2/internal/standby (interfaces: StateStore)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	standby "github.com/mongodb/mongodb-cli/mongocli/v2/internal/standby"
)

// MockStateStore is a mock of StateStore interface.
type MockStateStore struct {
	ctrl     *gomock.Controller
	recorder *MockStateStoreMockRecorder
}

// MockStateStoreMockRecorder is the mock recorder for MockStateStore.
type MockStateStoreMockRecorder struct {
	mock *MockStateStore
}

// NewMockStateStore creates a new mock instance.
func NewMockStateStore(ctrl *gomock.Controller) *MockStateStore {
	mock := &MockStateStore{ctrl: ctrl}
	mock.recorder = &MockStateStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStateStore) EXPECT() *MockStateStoreMockRecorder {
	return m.recorder
}

// ConditionalPutDRState mocks base method.
func (m *MockStateStore) ConditionalPutDRState(arg0 context.Context, arg1 *standby.RemoteDRState, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConditionalPutDRState", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConditionalPutDRState indicates an expected call of ConditionalPutDRState.
func (mr *MockStateStoreMockRecorder) ConditionalPutDRState(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConditionalPutDRState", reflect.TypeOf((*MockStateStore)(nil).ConditionalPutDRState), arg0, arg1, arg2)
}

// FetchDRState mocks base method.
func (m *MockStateStore) FetchDRState(arg0 context.Context) (*standby.RemoteDRState, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchDRState", arg0)
	ret0, _ := ret[0].(*standby.RemoteDRState)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FetchDRState indicates an expected call of FetchDRState.
func (mr *MockStateStoreMockRecorder) FetchDRState(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchDRState", reflect.TypeOf((*MockStateStore)(nil).FetchDRState), arg0)
}

// FullPath mocks base method.
func (m *MockStateStore) FullPath() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FullPath")
	ret0, _ := ret[0].(string)
	return ret0
}

// FullPath indicates an expected call of FullPath.
func (mr *MockStateStoreMockRecorder) FullPath() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FullPath", reflect.TypeOf((*MockStateStore)(nil).FullPath))
}
